general:
  refresh: 1
  keys:
    quit: "C-c"

projects:
  - name: webtechno
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 89379071
      monitor:
        address: "https://www.web-techno.net"
    widgets:
      - row:
          - col:
              size: "XL"
              elements:
                - name: ga.users
                  options:
                    start_date: "30daysAgo"
                    end_date: "10daysAgo"
          - col:
              size: "S"
              elements:
                - name: ga.realtime
                - name: mon.ping
                - name: mon.availability

  - name: sharetoall
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 176110148
      monitor:
        address: "https://www.sharetoall.com"
    widgets:
      - row:
          - col:
              size: "M"
              elements:
                - name: ga.realtime
                - name: mon.ping
                - name: mon.availability
          - col:
              size: "S"
              elements:
                - name: ga.users

  - name: bytestouuid
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 183738350
      monitor:
        address: "http://bytes-uuid-converter.net"
    widgets:
      - row:
          - col:
              size: "XL"
              elements:
                # - name: mon.ping
                # - name: mon.availability
                - name: ga.users
