general:
  refresh: 600
  keys:
    quit: "C-c"

projects:
  - name: webtechno
    services:
      google_search_console:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 89379071
        address: 'https://web-techno.net'
    widgets:
      - row:
          - col:
              size: "S"
              elements:
                - name: gsc.pages
                  options:
                    character_limit: 20
