general:
  refresh: 1
  keys:
    quit: "C-c"

projects:
  - name: webtechno
    title_options:
      border_color: magenta
      text_color: white
      size: XXL
      bold: true
      height: 20
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 89379071
      monitor:
        address: "https://www.web-techno.net"
    widgets:
      - row:
          - col:
              size: "S"
              elements:
                - name: ga.new_returning
                  options:
                    start_date: "3daysAgo"
                    end_date: "today"
                    title: "my super title"
                    first_color: "purple"
                    second_color: "pink"
          - col:
              size: "S"
              elements:
                - name: ga.users
                  options:
                    start_date: "3daysAgo"
                    end_date: "today"
                    title: "my super title"
                    bar_color: "yellow"
                    num_color: "white"
                    text_color: "grey"
                    border_color: "black"
                    height: 20
                    gap: 3
                    bar_widht: 8

      - row:
          - col:
              size: "XXL"
              elements:
                - name: ga.traffic_source
                  options:
                    start_date: "3daysAgo"
                    end_date: "today"
                    title: "my super title"
      - row:
          - col:
              size: "M"
              elements:
                - name: ga.pages
                  options:
                    title: "Pages"
                    length: 40
                    limit: 5
                    start_date: "3daysAgo"
                    end_date: "today"
                    global: true
          - col:
              size: "S"
              elements:
                - name: ga.realtime
                # - name: mon.ping
                - name: mon.availability

  - name: sharetoall
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 176110148
      monitor:
        address: "https://www.sharetoall.com"
    widgets:
      - row:
          - col:
              size: "M"
              elements:
                - name: ga.realtime
                # - name: mon.ping
                - name: mon.availability
          - col:
              size: "S"
              elements:
                - name: ga.users

  - name: bytestouuid
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 183738350
      monitor:
        address: "http://bytes-uuid-converter.net"
    widgets:
      - row:
          - col:
              size: "XL"
              elements:
                # - name: mon.ping
                # - name: mon.availability
                - name: ga.users
