general:
  keys:
    quit: "x"


projects:
  webtechno:
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 89379071
    widgets:
      - ga.realtime:
          size: "S"
        ga.users:
          size: "L"

  sharetoall:
    services:
      google_analytics:
        keyfile: goanalytics-dace33d3cede.json
        view_id: 176110148
    widgets:
      - ga.realtime:
          size: "S"
        ga.users:
          size: "L"
